modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/KenyMylankca/EnhancedArmaments/issues"
displayURL=""
logoFile="logo.png"
credits="TheXFactor117"
authors="JanneSoon"
[[mods]]
modId="enhancedarmaments"
version="1.4.2"
displayName="Enhanced Armaments"
updateJSONURL="https://minecraft.curseforge.com/projects/enhanced-armaments/files"
description='''
This mod gives your weapons and armors unique abilities by respect to the usage of them and your experience.
'''

[[dependencies.enhancedarmaments]]
	    modId="forge"
	    mandatory=true
	    versionRange="[25.0.141,)"
	    ordering="NONE"
	    side="BOTH"
		
[[dependencies.enhancedarmaments]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.13.2]"
	    ordering="NONE"
	    side="BOTH"