modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/KenyMylankca/EnhancedArmaments/issues"
displayURL=""
logoFile="logo.png"
credits="TheXFactor117"
authors="JanneSoon"
[[mods]]
modId="enhancedarmaments"
version="1.4.1"
displayName="Enhanced Armaments"
updateJSONURL="https://minecraft.curseforge.com/projects/enhanced-armaments/files"
description='''
This mod gives your weapons and armors unique abilities by respect to the usage of them and your experience.
'''
[[dependencies.enhancedarmaments]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[25,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.enhancedarmaments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"